GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "email": "user33@gmail.com",
    "password": "123456789"
}

###

POST http://localhost:3000/api/users/validate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEwZmUxYzdiMTBjYWU0ZTVkZjEzMWUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ1OTQ0MDkyLCJleHAiOjE3NDU5NTEyOTJ9.r1DSqquXUazNZdPXYMMl0osiKTAP2oAglDzl87Fz1M4

{
    "codigo_validacion": "429420"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "user33@gmail.com",
    "password": "123456789"
}

###
PUT http://localhost:3000/api/users/actualizarDatosPersonales
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEwZmUxYzdiMTBjYWU0ZTVkZjEzMWUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ1OTQ0Mjc5LCJleHAiOjE3NDU5NTE0Nzl9.Oadtf0ivDmCyL89GLI46L3BBMvAuQ4q3McLLaaD3CP8

{
    "nombre": "Jaime",
    "apellidos": "Robledo Sanchez",
    "nif": "69696969B"
}

###
PUT http://localhost:3000/api/users/actualizarDatosCompany
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEwZmUxYzdiMTBjYWU0ZTVkZjEzMWUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ1OTQ0Mjc5LCJleHAiOjE3NDU5NTE0Nzl9.Oadtf0ivDmCyL89GLI46L3BBMvAuQ4q3McLLaaD3CP8

{
  "autonomo": false,
  "company": {
        "name": "GOOGLE, SL",
        "cif": "AXXXXXXXX",
        "address": "Felipe II"
    }
}

###
PUT http://localhost:3000/api/users/actualizarDatosCompany
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEwZmUxYzdiMTBjYWU0ZTVkZjEzMWUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ1OTQ0MDkyLCJleHAiOjE3NDU5NTEyOTJ9.r1DSqquXUazNZdPXYMMl0osiKTAP2oAglDzl87Fz1M4

{
  "autonomo": true,
  "company": {
        "name": "Jaime Robledo Sanchez",
        "cif": "12345678A",
        "address": "Calle de la Paz"
    }
}

###
GET http://localhost:3000/api/users/porJWT
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEwZmUxYzdiMTBjYWU0ZTVkZjEzMWUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ1OTQ0MDkyLCJleHAiOjE3NDU5NTEyOTJ9.r1DSqquXUazNZdPXYMMl0osiKTAP2oAglDzl87Fz1M4

###
DELETE http://localhost:3000/api/users/deleteUser?soft=true
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhYjY3ZGYyZTE1YzViMDY3ZGE0MjYiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDM1Mzg5LCJleHAiOjE3NDM0NDI1ODl9.Dbsy7BV3JBco7kMFjCVOprhwwW7k1hxeEAFiczyBuSg

###
DELETE http://localhost:3000/api/users/deleteUser?soft=false
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhYjY3ZGYyZTE1YzViMDY3ZGE0MjYiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDM1Mzg5LCJleHAiOjE3NDM0NDI1ODl9.Dbsy7BV3JBco7kMFjCVOprhwwW7k1hxeEAFiczyBuSg

###
PUT http://localhost:3000/api/users/recuperarPassword
Content-Type: application/json

{
    "email": "user1@gmail.com"
}

###
PUT http://localhost:3000/api/users/validarRecuperacion
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhYjEwMWU2NmEzZTVlZDUwYjQ3ZDUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDQwNjY3LCJleHAiOjE3NDM0NDc4Njd9.pBLCevXZNnnIUGp2r7Xvzn6VZ0Wm4qA_yWCD9Tt2UMA

{
    "codigo_validacion": "646264"
}

###
PUT http://localhost:3000/api/users/restablecerPassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhYjEwMWU2NmEzZTVlZDUwYjQ3ZDUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDQwNjY3LCJleHAiOjE3NDM0NDc4Njd9.pBLCevXZNnnIUGp2r7Xvzn6VZ0Wm4qA_yWCD9Tt2UMA

{
    "password": "12345678912"
}

###
POST http://localhost:3000/api/users/invitar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhYjEwMWU2NmEzZTVlZDUwYjQ3ZDUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDQyMDk3LCJleHAiOjE3NDM0NDkyOTd9.X1fh3GqJjYE1pacJo5sxwhJO9qt8DCO0IFrgYIVuMV8

{
    "email": "guest1@gmail.com"
}

###
POST http://localhost:3000/api/users/logo 
Content-Type: multipart/form-data; boundary=boundary123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhYjEwMWU2NmEzZTVlZDUwYjQ3ZDUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDQyMDk3LCJleHAiOjE3NDM0NDkyOTd9.X1fh3GqJjYE1pacJo5sxwhJO9qt8DCO0IFrgYIVuMV8

--boundary123
Content-Disposition: form-data; name="image"; filename="pengu.jpg"
Content-Type: image/jpeg

< ./pengu.jpg
--boundary123-->

###
POST http://localhost:3000/api/clients/crearCliente
Content-Type: application/json

{
  "nombre": "ACS",
  "cif": "D52921210",
  "address": {
    "street": "Felipe II",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  },
  "usuarioId": "6810fe1c7b10cae4e5df131e"
}

###
PUT http://localhost:3000/api/clients/actualizarCliente/6811018bfb4172155a05651f
Content-Type: application/json

{
  "nombre": "FCC",
  "cif": "D52921210",
  "address": {
    "street": "Felipe II",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  },
  "usuarioId": "6810fe1c7b10cae4e5df131e"
}

###
GET http://localhost:3000/api/clients/listarClientes
Content-Type: application/json

###
GET http://localhost:3000/api/clients/encontrarCliente/6811018bfb4172155a05651f
Content-Type: application/json
