GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "email": "user0@gmail.com",
    "password": "1234567890"
}

###

POST http://localhost:3000/api/users/validate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RhY2ZiMTQ0YjIwOTg1YjcxNjE0ZDUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQyMzkzMjY1LCJleHAiOjE3NDI0MDA0NjV9.lm402YXHM6OBos3km0gSNObYjBDlOf-hhVmAPqpne7s

{
    "codigo_validacion": "802644"
}