GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "email": "user4@gmail.com",
    "password": "123456789"
}

###

POST http://localhost:3000/api/users/validate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEyNGE3NzI2YjRmN2FmODcwMTIxYTUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MDI5MTc1LCJleHAiOjE3NDYwMzYzNzV9.LQ64q3ib7IUlfYW53rWEJtj5qoEkVO0oz7fhasEQC6E

{
    "codigo_validacion": "965245"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "user4@gmail.com",
    "password": "123456789"
}

###
PUT http://localhost:3000/api/users/actualizarDatosPersonales
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEwZmUxYzdiMTBjYWU0ZTVkZjEzMWUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ1OTQ0Mjc5LCJleHAiOjE3NDU5NTE0Nzl9.Oadtf0ivDmCyL89GLI46L3BBMvAuQ4q3McLLaaD3CP8

{
    "nombre": "Jaime",
    "apellidos": "Robledo Sanchez",
    "nif": "69696969B"
}

###
PUT http://localhost:3000/api/users/actualizarDatosCompany
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEwZmUxYzdiMTBjYWU0ZTVkZjEzMWUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ1OTQ0Mjc5LCJleHAiOjE3NDU5NTE0Nzl9.Oadtf0ivDmCyL89GLI46L3BBMvAuQ4q3McLLaaD3CP8

{
  "autonomo": false,
  "company": {
        "name": "GOOGLE, SL",
        "cif": "AXXXXXXXX",
        "address": "Felipe II"
    }
}

###
PUT http://localhost:3000/api/users/actualizarDatosCompany
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEwZmUxYzdiMTBjYWU0ZTVkZjEzMWUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ1OTQ0MDkyLCJleHAiOjE3NDU5NTEyOTJ9.r1DSqquXUazNZdPXYMMl0osiKTAP2oAglDzl87Fz1M4

{
  "autonomo": true,
  "company": {
        "name": "Jaime Robledo Sanchez",
        "cif": "12345678A",
        "address": "Calle de la Paz"
    }
}

###
GET http://localhost:3000/api/users/porJWT
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEwZmUxYzdiMTBjYWU0ZTVkZjEzMWUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ1OTQ0MDkyLCJleHAiOjE3NDU5NTEyOTJ9.r1DSqquXUazNZdPXYMMl0osiKTAP2oAglDzl87Fz1M4

###
DELETE http://localhost:3000/api/users/deleteUser?soft=true
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODExNGE0ODkxMGNjZmQ5ZTAyYzRjMmUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ1OTYzNTkyLCJleHAiOjE3NDU5NzA3OTJ9.EYE85mzeEF78PSrKf2rkIWcH7qN1KOzsOo8snEcTgqo

###
DELETE http://localhost:3000/api/users/deleteUser?soft=false
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODExNGE0ODkxMGNjZmQ5ZTAyYzRjMmUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ1OTYzNTkyLCJleHAiOjE3NDU5NzA3OTJ9.EYE85mzeEF78PSrKf2rkIWcH7qN1KOzsOo8snEcTgqo

###
PUT http://localhost:3000/api/users/recuperarPassword
Content-Type: application/json

{
    "email": "user1@gmail.com"
}

###
PUT http://localhost:3000/api/users/validarRecuperacion
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhYjEwMWU2NmEzZTVlZDUwYjQ3ZDUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDQwNjY3LCJleHAiOjE3NDM0NDc4Njd9.pBLCevXZNnnIUGp2r7Xvzn6VZ0Wm4qA_yWCD9Tt2UMA

{
    "codigo_validacion": "646264"
}

###
PUT http://localhost:3000/api/users/restablecerPassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhYjEwMWU2NmEzZTVlZDUwYjQ3ZDUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDQwNjY3LCJleHAiOjE3NDM0NDc4Njd9.pBLCevXZNnnIUGp2r7Xvzn6VZ0Wm4qA_yWCD9Tt2UMA

{
    "password": "12345678912"
}

###
POST http://localhost:3000/api/users/invitar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhYjEwMWU2NmEzZTVlZDUwYjQ3ZDUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDQyMDk3LCJleHAiOjE3NDM0NDkyOTd9.X1fh3GqJjYE1pacJo5sxwhJO9qt8DCO0IFrgYIVuMV8

{
    "email": "guest1@gmail.com"
}

###
POST http://localhost:3000/api/users/logo 
Content-Type: multipart/form-data; boundary=boundary123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhYjEwMWU2NmEzZTVlZDUwYjQ3ZDUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDQyMDk3LCJleHAiOjE3NDM0NDkyOTd9.X1fh3GqJjYE1pacJo5sxwhJO9qt8DCO0IFrgYIVuMV8

--boundary123
Content-Disposition: form-data; name="image"; filename="pengu.jpg"
Content-Type: image/jpeg

< ./pengu.jpg
--boundary123-->

###
POST http://localhost:3000/api/clients/crearCliente
Content-Type: application/json

{
  "nombre": "Amazon",
  "cif": "D89920110",
  "address": {
    "street": "Felipe I",
    "number": 42,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  },
  "usuarioId": "68124a7726b4f7af870121a5"
}

###
PUT http://localhost:3000/api/clients/actualizarCliente/6812590fa1c02f5cdd12bf94
Content-Type: application/json

{
  "nombre": "Amazon",
  "cif": "D89920110",
  "address": {
    "street": "Maranillo 2",
    "number": 62,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  },
  "usuarioId": "68124a7726b4f7af870121a5"
}

###
GET http://localhost:3000/api/clients/listarClientes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEyNGE3NzI2YjRmN2FmODcwMTIxYTUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MDMyMTc5LCJleHAiOjE3NDYwMzkzNzl9.BOW43aMc5xDssZAPaJwfx-53CRxjOwfGxggybRJzqLE

###
GET http://localhost:3000/api/clients/encontrarCliente/6812599ea1c02f5cdd12bfa0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEyNGE3NzI2YjRmN2FmODcwMTIxYTUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MDMyMTc5LCJleHAiOjE3NDYwMzkzNzl9.BOW43aMc5xDssZAPaJwfx-53CRxjOwfGxggybRJzqLE

###
DELETE http://localhost:3000/api/clients/borrarCliente/6812599ea1c02f5cdd12bfa0?soft=true
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEyNGE3NzI2YjRmN2FmODcwMTIxYTUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MDMyMTc5LCJleHAiOjE3NDYwMzkzNzl9.BOW43aMc5xDssZAPaJwfx-53CRxjOwfGxggybRJzqLE

###
DELETE http://localhost:3000/api/clients/borrarCliente/6812599ea1c02f5cdd12bfa0?soft=false
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEyNGE3NzI2YjRmN2FmODcwMTIxYTUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MDMyMTc5LCJleHAiOjE3NDYwMzkzNzl9.BOW43aMc5xDssZAPaJwfx-53CRxjOwfGxggybRJzqLE

###
GET http://localhost:3000/api/clients/listarArchivados
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEyNGE3NzI2YjRmN2FmODcwMTIxYTUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MDMyMTc5LCJleHAiOjE3NDYwMzkzNzl9.BOW43aMc5xDssZAPaJwfx-53CRxjOwfGxggybRJzqLE

###
PATCH  http://localhost:3000/api/clients/recuperarCliente/6812599ea1c02f5cdd12bfa0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEyNGE3NzI2YjRmN2FmODcwMTIxYTUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2MDMyMTc5LCJleHAiOjE3NDYwMzkzNzl9.BOW43aMc5xDssZAPaJwfx-53CRxjOwfGxggybRJzqLE
